// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:49056a14-4fe5-4a0f-94e2-549e498ddc8e',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': 'f6888152814242a6b735cf98455adbfa',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '83343d0f-f3b3-45cf-8e28-9d26346ca047',
    'aws_project_name': 'FoodLens',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'foodlens-mobilehub-618891941',
}

export default awsmobile;
