// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:49056a14-4fe5-4a0f-94e2-549e498ddc8e';
var aws_cognito_region = 'us-east-1';
var aws_mobile_analytics_app_id = 'f6888152814242a6b735cf98455adbfa';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '83343d0f-f3b3-45cf-8e28-9d26346ca047';
var aws_project_name = 'FoodLens';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'foodlens-mobilehub-618891941';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
